# Copyright (c) 2026 Samsung Electronics Co., Ltd.
# SPDX-License-Identifier: Apache-2.0

from typing import Optional

def NanoQuantConfig(
    # model id
    model_id: str = "meta-llama/Llama-2-7b-hf",
    # quant precision
    bits: float = 1.0,
    # calib
    seed: int = 0,
    num_calib_samples: int = 128,
    calib_dataset: str = "wikitext2",
    calib_shrinkage: float = 0.4,
    calib_strategy: str = "online",
    seqlen: int = 2048,
    device_map: str = "cpu",
    # tune_nonfact
    tune_nonfact: bool = True,
    nonfact_lr: float = 1e-4,
    nonfact_batch_size: int = 4,
    nonfact_epochs: int = 8,
    # fact (admm)
    admm_type: str = "nanoquant",
    admm_outer_iters: int = 400,
    admm_inner_iters: int = 5,
    admm_reg: float = 3e-2,
    admm_penalty_scheduler: str = "linear",
    admm_print_steps: bool = False,
    # tune_fact
    tune_fact: bool = True,
    fact_binary_lr: float = 1e-5,
    fact_scale_lr: float = 1e-5,
    fact_bias_lr: float = 1e-5,
    fact_batch_size: int = 1,
    fact_epochs: int = 8,
    # tune_model
    tune_model: bool = True,
    model_kd_lr: float = 1e-5,
    model_kd_batch_size: int = 1,
    model_kd_epochs: int = 8,
    # optional runtime controls appended to preserve positional callers
    block_io_batch_size: int = 4,
    admm_warm_start_iters: int = 2,
    log_reconstruction_error: bool = False,
    model_kd_num_samples: int = 64,
    eval_after_each_block: bool = False,
    admm_early_stop: bool = True,
    admm_min_outer_iters: int = 120,
    admm_check_interval: int = 10,
    admm_convergence_tolerance: float = 2e-3,
    admm_stable_sign_tolerance: float = 1e-3,
    admm_rho_stop_threshold: float = 0.85,
    model_kd_vocab_chunk_size: int = 4096,
    model_kd_pack_factors: bool = False,
    rank_allocation: str = "sensitivity",
    require_fast_linear_attention: bool = False,
    attn_implementation: str = "auto",
    tune_schedule: str = "sequential",
    layer_epoch_schedule: bool = True,
    refresh_input_stats: bool = True,
    resume_dir: str = "",
    rank_budget: str = "nominal",
    rank_probe_candidates: int = 0,
    rank_probe_iters: int = 50,
    correlation_block_size: int = 0,
    correlation_layers: str = "mlp.down_proj",
    nonfact_plateau_tolerance: float = 0.0,
    nonfact_plateau_min_epochs: int = 3,
    nonfact_plateau_patience: int = 2,
    model_revision: Optional[str] = None,
) -> dict:
    return {
        # model id
        "model_id": model_id,
        "model_revision": model_revision,
        # quant precision
        "bits": bits,
        "rank_allocation": rank_allocation,
        # calibration
        "seed": seed,
        "num_calib_samples": num_calib_samples,
        "calib_dataset": calib_dataset,
        "calib_shrinkage": calib_shrinkage,
        "calib_strategy": calib_strategy,
        "seqlen": seqlen,
        "device_map": device_map,
        "require_fast_linear_attention": require_fast_linear_attention,
        "attn_implementation": attn_implementation,
        "tune_schedule": tune_schedule,
        "layer_epoch_schedule": layer_epoch_schedule,
        "refresh_input_stats": refresh_input_stats,
        "resume_dir": resume_dir,
        "rank_budget": rank_budget,
        "rank_probe_candidates": rank_probe_candidates,
        "rank_probe_iters": rank_probe_iters,
        "correlation_block_size": correlation_block_size,
        "correlation_layers": correlation_layers,
        "nonfact_plateau_tolerance": nonfact_plateau_tolerance,
        "nonfact_plateau_min_epochs": nonfact_plateau_min_epochs,
        "nonfact_plateau_patience": nonfact_plateau_patience,
        "block_io_batch_size": block_io_batch_size,
        "eval_after_each_block": eval_after_each_block,
        # tune_nonfact
        "tune_nonfact": tune_nonfact,
        "nonfact_lr": nonfact_lr,
        "nonfact_batch_size": nonfact_batch_size,
        "nonfact_epochs": nonfact_epochs,
        # fact (admm)
        "admm_type": admm_type,
        "admm_outer_iters": admm_outer_iters,
        "admm_inner_iters": admm_inner_iters,
        "admm_warm_start_iters": admm_warm_start_iters,
        "admm_early_stop": admm_early_stop,
        "admm_min_outer_iters": admm_min_outer_iters,
        "admm_check_interval": admm_check_interval,
        "admm_convergence_tolerance": admm_convergence_tolerance,
        "admm_stable_sign_tolerance": admm_stable_sign_tolerance,
        "admm_rho_stop_threshold": admm_rho_stop_threshold,
        "admm_reg": admm_reg,
        "admm_penalty_scheduler": admm_penalty_scheduler,
        'admm_print_steps': admm_print_steps,
        "log_reconstruction_error": log_reconstruction_error,
        # tune_fact
        "tune_fact": tune_fact,
        "fact_binary_lr": fact_binary_lr,
        "fact_scale_lr": fact_scale_lr,
        "fact_bias_lr": fact_bias_lr,
        "fact_batch_size": fact_batch_size,
        "fact_epochs": fact_epochs,
        # tune_model
        "tune_model": tune_model,
        "model_kd_lr": model_kd_lr,
        "model_kd_batch_size": model_kd_batch_size,
        "model_kd_num_samples": model_kd_num_samples,
        "model_kd_vocab_chunk_size": model_kd_vocab_chunk_size,
        "model_kd_pack_factors": model_kd_pack_factors,
        "model_kd_epochs": model_kd_epochs,
    }
